[package]
name = "stove"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unreal_asset = { git = "https://github.com/astrotechies/unrealmodding", package = "unreal_asset" }
miniquad = "*"
egui-miniquad = "*"
egui = "*"
egui-notify = "*"
native-dialog = "*"
platform-dirs = "*"
