[package]
name = "stove"
authors = ["spuds"]
repository = "https://github.com/bananaturtlesandwich/stove"
readme = "README.md"
version = "0.2.0"
edition = "2021"
description = "An editor for cooked unreal engine 4 map files"

[dependencies]
unreal_asset = { git = "https://github.com/astrotechies/unrealmodding", package = "unreal_asset" }
glam = { version = "*", features = ["fast-math"] }
miniquad = "*"
egui = "*"
egui-miniquad = "*"
# use this fork until the PR is accepted
egui-gizmo = { git = "https://github.com/matthiascy/egui-gizmo" }
egui-notify = "*"
egui_file = "*"
dirs = "*"
byteorder = "*"

[build-dependencies]
winres = "*"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
discord-rich-presence = "*"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
