[package]
name = "stove"
authors = ["spuds"]
repository = "https://github.com/bananaturtlesandwich/stove"
readme = "README.md"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unreal_asset = { git = "https://github.com/astrotechies/unrealmodding", package = "unreal_asset" }
miniquad = "*"
egui-miniquad = "*"
egui = "*"
egui-notify = "*"
native-dialog = "*"
dirs = "*"

[target.'cfg(windows)'.build-dependencies]
winres = "*"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
