[package]
name = "stove"
authors = ["spuds"]
repository = "https://github.com/bananaturtlesandwich/stove"
description = "an editor for cooked unreal engine 4 map files"
readme = "README.md"
version = "0.7.1"
edition = "2021"

[dependencies]
unreal_asset = { git = "https://github.com/astrotechies/unrealmodding", package = "unreal_asset" }
unpak = { version = "1.0", features = ["asset-paths"] }
glam = { version = "0.23", features = ["fast-math"] }
miniquad = "0.3"
egui = "0.21"
egui-miniquad = "0.14"
egui-notify = "0.6"
egui_file = "0.8"
byteorder = "1.4"
hashbrown = "0.13"
hex = "0.4"

[build-dependencies]
winres = "0.1"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
discord-rich-presence = "0.2"
autoupdater = "0.3"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
