on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.6.0
      - name: build
        run: cargo build -r --verbose
      - name: rename
        run: mv target/release/stove target/release/stove-ubuntu
      - name: archive
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ubuntu
          path: target/release/stove-ubuntu

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2.6.0
      - name: build
        run: cargo build -r --verbose
      - name: rename
        run: mv target/release/stove target/release/stove-macos
      - name: archive
        uses: actions/upload-artifact@v3.1.1
        with:
          name: macos
          path: target/release/stove-macos

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2.6.0
      - name: build
        run: cargo build -r --verbose
      - name: archive
        uses: actions/upload-artifact@v3.1.1
        with:
          name: windows
          path: target/release/stove.exe
