on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.6.0
      - name: build
        run: cargo build -r --verbose
      - name: archive
        uses: actions/upload-artifact@v3.1.1
        with:
          name: linux
          path: target/release/stove

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2.6.0
      - name: build
        run: cargo build -r --verbose
      - name: archive
        uses: actions/upload-artifact@v3.1.1
        with:
          name: macos
          path: target/release/stove

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2.6.0
      - name: build
        run: cargo build -r --verbose
      - name: archive
        uses: actions/upload-artifact@v3.1.1
        with:
          name: windows
          path: target/release/stove.exe
